### ISSUE TITLE
Getting all messages from socket

### ISSUE THREAD

**Issue by nikolayr1** [voryx/thruway.js#12]
Hello.
How can i subscribe on all socket messages to get some data out of them?
`node_modules/thruway.js/src/Transport/WebSocketTransport.js`
![image](https://user-images.githubusercontent.com/11279857/35109326-b7a4ea0e-fc7e-11e7-9a3f-a715f688bbf3.png)
it seems like there is no way to do it, because output field of transport is private.

**Comment by davidwdan** [comment]
There is no supported way to do this right now.  The only way is to implement your own websocket transport and expose what you need.
