### ISSUE TITLE
CALL with progressive Result, value in last progress=false message are lost by takeWhile filter

### ISSUE THREAD

**Issue by gajanak** [voryx/thruway.js#13]
Hello,

I evaluate the thruway.js WAMP Client (Angular2) and noticed that the last CALL Result's are missing if a CALL is progressive.

Szenario:
CALLER -(CALL)-> DEALER
CALLER <-(RESULT progress=true)- DEALER
CALLER <-(RESULT progress=true)- DEALER
CALLER <-(RESULT progress=true)- DEALER
CALLER <-(RESULT )- DEALER

I noticed in CallObservable.js Line 57  CallObservable.prototype._subscribe

```ts
      const resultMsg = msg
            .takeWhile(m => m.details.progress || false)
            .finally(() => this.completed = true)
              .share();
```

The TakeWhile seems not to be inclusive ... the last message is not forwarded to next(value) on subscribers. Perhaps the problem is at a different point... but adding a workaround after a 5-minute-rxjs-tutorial is adding this:

```ts
 var resultMsg = msg
            .do (function (m) { 
                if (m && ! m.details.progress || false)
                {
                        this.next(null);
                }
            })
            .takeWhile(function (m) { 
                return m /*&& m.details.progress || false*/; 
            })
            .finally(function () { return _this.completed = true; })
            .share();
```

I hope this is right: next(null) will inject an empty message -> which will stop takeWhile.....

Any Comments ? I don't know exact if this is a 'good' solution ;)

Update:
used '1.3.0-beta2': '2018-02-22T13:13:37.287Z' installed by npm

**Comment by davidwdan** [comment]
The thruway.js progress isn't 100% compatible with other wamp clients.  We concat an additional blank message at the end of the progress sequence so we know when the far end observable has completed.  We don't want it to be inclusive, since the last message is used only for signaling. 

https://github.com/voryx/thruway.js/blob/master/src/Observable/RegisterObservable.ts#L129

If you use thruway.js with `progressiveRegister` and `progressiveCall` everything *should* work.

What client are you using to register the rpc?

**Comment by gajanak** [comment]
Own WAMP Client/Server Implementation in c++. That's why i Know the protocol. Perhaps the library should be WAMP Standard Conform, and if thruway dealer is detected, only empty messages are filtered.

**Comment by davidwdan** [comment]
I'll play around with this a bit.  It shouldn't be too much trouble to get it to work with other clients.

**Comment by davidwdan** [comment]
@gajanak can you test it with 1.3.0-beta3?

**Comment by gajanak** [comment]
Soory for little delay. works. ;)
