### ISSUE TITLE
thruway.auth.invalid_response_to_hello

### ISSUE THREAD

**Issue by dderdaniel** [voryx/thruway.js#21]
Hey,

can anyone help me with the wampcra auth method?
Why I'm getting an "thruway.auth.invalid_response_to_hello" response?

Send:
`[1,"project",{"authmethods":["wampcra"],"roles":{"caller":{"features":{"caller_identification":true,"progressive_call_results":true,"call_canceling":true}},"callee":{"features":{"caller_identification":true,"pattern_based_registration":true,"shared_registration":true,"progressive_call_results":true,"registration_revocation":true,"call_canceling":true}},"publisher":{"features":{"publisher_identification":true,"subscriber_blackwhite_listing":true,"publisher_exclusion":true}},"subscriber":{"features":{"publisher_identification":true,"pattern_based_subscription":true,"subscription_revocation":true}}}}]`

Receive: `[3,{},"thruway.auth.invalid_response_to_hello"]`

My code (clientside):
```typescript
// Thruway.js
@Injectable()
export class WebsocketService extends Client {

  constructor() {
    super(((environment.production) ? 'wss://' : 'ws://') + window.location.host + ':' + 1337 + '/', 'project', {
      authmethods: ['wampcra']
    });
    this.onChallenge((challenge: Observable<ChallengeMessage>) => {
      return new Observable<string>(observer => observer.next(localStorage.getItem('auth')));
    });
  }

}
```

My code (serverside):
```php
        // Thruway
        $this->loop = Factory::create();
        $this->router = new Router($this->loop);

        $this->websocket = new RatchetTransportProvider('0.0.0.0', WS_PORT);
        $this->router->addTransportProvider($this->websocket);

        $this->authManager = new AuthenticationManager();
        $this->router->registerModule($this->authManager);

        $this->authProvider = new WampCraAuthProvider(['project'], $this->loop);
        $this->authProvider->setUserDb(new AuthDb());

        $this->router->addInternalClient($this->authProvider);

        $this->router->getRealmManager()->addRealm(new Realm('project'));
        $this->router->getRealmManager()->setAllowRealmAutocreate(true);

        $this->router->start();
```

**Comment by davidwdan** [comment]
What are the versions of thruway.js and the Thruway Router?

**Comment by davidwdan** [comment]
I haven't used wampcra in years and have never tested it with thruway.js, but I believe that you need to provide the authid when you create the client. 

```JS
// Thruway.js
@Injectable()
export class WebsocketService extends Client {

  constructor() {
    super(((environment.production) ? 'wss://' : 'ws://') + window.location.host + ':' + 1337 + '/', 'project', {
      authmethods: ['wampcra'],
      authid: 'daniel'
    });
    this.onChallenge((challenge: Observable<ChallengeMessage>) => {
      return new Observable<string>(observer => observer.next(localStorage.getItem('auth')));
    });
  }

}
```
