### ISSUE TITLE
Best way to throw an exception inside a registered function

### ISSUE THREAD

**Issue by creat-or** [voryx/thruway.js#24]
When I try to throw an Exception like 

```Typescript
async function trySomething(a, b) {
  // try something
  throw(new Error('hello'));
}

wamp.register('add.rpc', trySomething).subscribe();
```

then the Error I get on the other side is
```Javascript
Error {
  error: 'thruway.error.invocation_exception',
  args: [],
  kwargs: {}
}
```

Is there a way to raise another error or provide details about the Error on side that calls the function?

Thanks!

**Comment by mbonneau** [comment]
I believe throwing a `WampInvocationException` will allow you to control the WAMP error details that get sent back to the caller.

**Comment by creat-or** [comment]
Thank you, but for that I would need an `InvocationMessage` and for that some information that I do not have at that point.

**Comment by creat-or** [comment]
OK, it works like that
```Typescript
throw new WampInvocationException(new InvocationMessage(InvocationMessage.MSG_INVOCATION, 0, {}, args, argskw),
      'my.error.trysomething',
      args,
      argskw,
      {
        error: `Some error description`
      }
    );
```
that on the other side this releases:
```Javascript
Error {
  error: 'my.error.trysomething',
  args: [],
  kwargs: { code: 'd126' }
}
```

Seems like the only information that I don't have at that point is the `registrationId`. Don't I need that? And the details are not passed, but I guess that's by design?

**Comment by davidwdan** [comment]
It should be easier than that to throw an exception. I’ll take a look at it
later today.

**Comment by davidwdan** [comment]
This should work:

```JS
async function trysomething(a, b) {
    throw new WampErrorException('my.error.trysomething', ['arg1', 'arg2']);
}
```

How do you plan on using the `registrationId`?

We limit what is sent back with the error message to limit the possibility of accidentally leaking information.  You have fine grain control over everything with `WampErrorExeption`.

**Comment by creat-or** [comment]
Oh yes, that should be sufficient.

I do not need the `registrationId`. I just would have needed it on using `WampInvocationException` with `InvocationMessage`.

Thank you! :)
