### ISSUE TITLE
react-native support

### ISSUE THREAD

**Issue by esistgut** [voryx/thruway.js#25]
Just wondering if this library has been tested with react-native or if you plan to do it.

**Comment by davidwdan** [comment]
We use it with React Native.  Are you running into an issue or are you looking for some specific functionality?

**Comment by esistgut** [comment]
Just couldn't find any reference to react-native within this repository so I assumed it was unexplored territory. Autobahn.js has react-native related issues (https://github.com/crossbario/autobahn-js/issues/321 https://github.com/crossbario/autobahn-js/issues/372) so I tought explicit support had to be planned.
Is this compatible with Expo too?

**Comment by davidwdan** [comment]
It should work fine with Expo.
```JS
export const wamp = new Thruway.Client('wss://localhost:9090', 'realm1',);

function Example({id}) {

    // Using https://github.com/LeetCode-OpenSource/rxjs-hooks
    const someRPCValue = useObservable(() => wamp.call('test.rpc', [id]).map(res => res.args[0]));
    const someTopicValue = useObservable(() => wamp.topic('test.topic', [id]).map(res => res.args[0]));
    
    return (
        <View>
            <Text>{someRPCValue}</Text>
            <Text>{someTopicValue}</Text>
        </View>
    )
}
```
