### ISSUE TITLE
.call argskw expected to be an array?

### ISSUE THREAD

**Issue by creat-or** [voryx/thruway.js#8]
Thank you very much for this library! Just came to check it out and try the first steps. On Client.call I think there is a mistake, because the library expects argskw to be an array.

But thanks, seems to be very promising for using Wamp with Angular :)

**Comment by davidwdan** [comment]
You are correct. Do you want to create a pull request?

**Comment by creat-or** [comment]
Could you make another patch version vor this? :)

**Comment by davidwdan** [comment]
I'll try to get a release out within the next couple of days

**Comment by davidwdan** [comment]
Done.  Let me know if you have any issues.
